# Generated by Django 5.0.2 on 2024-02-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="index_order",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
