# Generated by Django 5.0.2 on 2024-03-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_paragraph_index_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="paragraph",
            name="image_url",
            field=models.TextField(default=None),
        ),
    ]
