# Generated by Django 5.0.2 on 2024-03-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_paragraph_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="C:\\darthpedro\\Programacion\\Blog\\mediafiles"
                    ),
                ),
            ],
        ),
    ]
